spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/qingyun_db?characterEncoding=utf-8&useSSL=false


  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  http:
    multipart:
      enabled: true
      max-file-size: 5242880
server:
  port: 8899





