spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/qingyun_db2?characterEncoding=utf-8&useSSL=false


  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false

